### ISSUE TITLE
嗨 貌似没有文件和图片上传处理

### ISSUE THREAD

**Issue by ShootMachine** [bawn/LCNetwork#1]
嗨, 没有图片及文件上传的处理。还有一个问题
// 请求时间
- (NSString *)requestTime{
  return @"15:00";
  }
  这个方法设置的是每天定时调用接口 还是可以设置一个未来时间 只调用一次接口？

**Comment by bawn** [comment]
@ShootMachine 已修复，看demo中的Api3这个类

**Comment by bawn** [comment]
@ShootMachine 时间问题是这样的，比如你设置的是15：00，如果是第一次调用这个接口，那么无论是什么时间都会执行，到15：00之前的调用都会被执行，等到用户在15：10的时候调用的时候，就会记录这个时间，直到第二天的15：00之前用户调用都会不会执行。

使用场景：余额宝的利息是有个结算时间，比如在每天的15：00，在当天如果调用过，就不需要再调用了，这种方式可以减轻服务器压力
