### ISSUE TITLE
Api1按钮一点就崩溃。

### ISSUE THREAD

**Issue by ZsIsMe** [bawn/LCNetwork#2]
2015-11-05 21:59:37.410 LCNetworkDemo[7399:586126] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[**NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
**\* First throw call stack:
(
    0   CoreFoundation                      0x000000010d574f45 __exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010cfeedeb objc_exception_throw + 48
    2   CoreFoundation                      0x000000010d477eae -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 318
    3   CoreFoundation                      0x000000010d48a21b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
    4   LCNetworkDemo                       0x000000010b0200b8 -[Api2 requestArgument] + 136
    5   LCNetworkDemo                       0x000000010b0209cf -[LCNetworkAgent addRequest:] + 863
    6   LCNetworkDemo                       0x000000010b0286d8 -[LCBaseRequest start] + 104
    7   LCNetworkDemo                       0x000000010b02664a -[LCBatchRequest start] + 506
    8   LCNetworkDemo                       0x000000010b026824 -[LCBatchRequest startWithCompletionBlockWithSuccess:failure:] + 116
    9   LCNetworkDemo                       0x000000010b02457f -[ViewController api1Press:] + 815
    10  UIKit                               0x000000010bae8e91 -[UIApplication sendAction:to:from:forEvent:] + 92
    11  UIKit                               0x000000010bc544d8 -[UIControl sendAction:to:forEvent:] + 67
    12  UIKit                               0x000000010bc547a4 -[UIControl _sendActionsForEvents:withEvent:] + 311
    13  UIKit                               0x000000010bc538d4 -[UIControl touchesEnded:withEvent:] + 601
    14  UIKit                               0x000000010bb56ed1 -[UIWindow _sendTouchesForEvent:] + 835
    15  UIKit                               0x000000010bb57c06 -[UIWindow sendEvent:] + 865
    16  UIKit                               0x000000010bb072fa -[UIApplication sendEvent:] + 263
    17  UIKit                               0x000000010bae1abf _UIApplicationHandleEventQueue + 6844
    18  CoreFoundation                      0x000000010d4a1011 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION** + 17
    19  CoreFoundation                      0x000000010d496f3c __CFRunLoopDoSources0 + 556
    20  CoreFoundation                      0x000000010d4963f3 __CFRunLoopRun + 867
    21  CoreFoundation                      0x000000010d495e08 CFRunLoopRunSpecific + 488
    22  GraphicsServices                    0x0000000110289ad2 GSEventRunModal + 161
    23  UIKit                               0x000000010bae730d UIApplicationMain + 171
    24  LCNetworkDemo                       0x000000010b02835f main + 111
    25  libdyld.dylib                       0x000000010dfff92d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by bawn** [comment]
@ZsIsMe 已修复
