### ISSUE TITLE
通过协议获取LCRequestSerializerType方法有误

### ISSUE THREAD

**Issue by XB-Paul** [bawn/LCNetwork#4]
判断协议是否响应方法之后，应该是通过协议方法得到LCRequestSerializerType  然后比较。作者应该是笔误写错了  
 if ([request.child respondsToSelector:@selector(requestSerializerType)]) {
        if ([request.child respondsToSelector:@selector(requestSerializerType)] == LCRequestSerializerTypeHTTP) {
            self.manager.requestSerializer = [AFHTTPRequestSerializer serializer];
        }
        else{
            _manager.requestSerializer = [AFJSONRequestSerializer serializer];
        }
    }

**Comment by bawn** [comment]
@XB-Paul 谢谢提醒，已修复

**Comment by XB-Paul** [comment]
1、LCBaseRequest.h中为什么要定义LCAPIRequest协议来定义请求的属性，这个协议都是在子类实现的，为什么不直接定义为LCBaseRequest的实例方法呢？

2、这部分代码：
    1）
        request.sessionDataTask = [self.manager GET:url parameters:argument progress:^(NSProgress \* _Nonnull downloadProgress) {
            [self handleRequestProgress:downloadProgress request:request];
        } success:^(NSURLSessionDataTask \* _Nonnull task, id  _Nullable responseObject) {
            request.responseJSONObject = responseObject;
            [self handleRequestSuccess:task];
        } failure:^(NSURLSessionDataTask \* _Nullable task, NSError \* _Nonnull error) {
            [self handleRequestFailure:task];
        }];

```
2）
```
- (void)handleRequestSuccess:(NSURLSessionDataTask *)sessionDataTask{
  NSString *key = [self keyForRequest:sessionDataTask];
  LCBaseRequest *request = _requestsRecord[key];
  if (request) {
  ……
  }
  }

为什么使用handleRequestProgress: request: 方法时 可以把request对象当参数传过去；
而使用handleRequestSuccess: 方法时，却是通过取字典里的那个request对象呢

**Comment by bawn** [comment]
用协议的方式参考的是这篇博客：http://casatwy.com/iosying-yong-jia-gou-tan-wang-luo-ceng-she-ji-fang-an.html?utm_source=tuicool

引用其中一段话是这样的

> 简单说就是在init的时候检查自己是否符合预先设计的子类的protocol，这就要求所有子类必须遵守这个protocol，所有针对父类的重载、覆盖也都以这个protocol为准，protocol以外的方法不允许重载、覆盖。而在父类的代码里，可以不必遵守这个protocol，保持了未来维护的灵活性。
> 这么做的好处就是避免了父类写空方法，同时也给子类带上了紧箍咒：要想当我的孩子，就要遵守这些规矩，不能乱来。业务方在实现子类的时候，就可以根据protocol中的方法去一一实现，然后约定就比较好做了：不允许重载父类方法，只允许选择实现或不实现protocol中的方法

如果使用实例方法，那么对子类的控制都需要通过重写父类方法去实现，实际操作中往往不知道那些方法该重写，那些不需要重写，而且也不清楚重写带来的后果（这可能也取决于作者文档写的详细情况），而且子类不应该直接父类的实现细节，只需要自己该干什么就行了，可以说重载破坏一定的封装性，另外关于重载可能会带来另外一些问题，请参考 http://casatwy.com/tiao-chu-mian-xiang-dui-xiang-si-xiang-yi-ji-cheng.html

第二个问题，我只是沿用了YTKNetwork的做法，具体可以参考[YTKNetwork](https://github.com/yuantiku/YTKNetwork)

**Comment by XB-Paul** [comment]
唐巧他们写的YTKNetwork中使用AFNetworking是低版本，没涉及到请求过程中的NSProgress。
他为什么通过存request然后读request的方式来获取request，而不是直接通过传参来传递request，我不是很清楚。

> 在 2016年1月14日，上午9:32，Bawn <notifications@github.com <mailto:notifications@github.com>> 写道：
> 
> YTKNetwork
